// Auth token will be used to generate a meeting and connect to it
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiIzZTk4OWQxMS1jZjU0LTQxZTQtOTA0OS05NzFiZjQyNzYwZTMiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTcyOTEwMTMyMiwiZXhwIjoxODg2ODg5MzIyfQ.cOkX9xY7scmFwbrLyT8SuLypDQe0kk2LUNbMD4kSa5o";
